syz-cluster: add GKE overlays
The overlays generate the configs for the deployment in the GKE
environment.

diff --git a/syz-cluster/Makefile b/syz-cluster/Makefile
--- a/syz-cluster/Makefile
+++ b/syz-cluster/Makefile
@@ -63,10 +63,26 @@ restart-spanner: build-db-mgmt
 	minikube addons enable cloud-spanner;
 	./run-local.sh db-mgmt migrate
 
-SUBSTITUTE_VARS := '$$IMAGE_PREFIX $${IMAGE_TAG}'
+
+SUBSTITUTE_VARS := '$$IMAGE_PREFIX $$IMAGE_TAG $$SPANNER_DATABASE_URI $$BLOB_STORAGE_GCS_BUCKET'
 
 k8s-config-dev:
 	@kubectl kustomize ./overlays/minikube/ | IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${IMAGE_TAG} envsubst ${SUBSTITUTE_VARS}
 
+k8s-config-gke: ensure-spanner-database-uri-env ensure-blob-storage-env
+	@kubectl kustomize ./overlays/gke/ | IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${IMAGE_TAG} envsubst ${SUBSTITUTE_VARS}
+
 migrate-job.yaml: ensure-spanner-database-uri-env
-	@cat db-mgmt/migrate-job.yaml | IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${IMAGE_TAG} envsubst ${SUBSTITUTE_VARS}
+	@cat db-mgmt/migrate-job.yaml | IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${IMAGE_TAG} envsubst
+
+ensure-spanner-database-uri-env:
+	@if [ -z "${SPANNER_DATABASE_URI}" ]; then \
+                echo "Error: SPANNER_DATABASE_URI must be defined."; \
+                exit 1; \
+        fi
+
+ensure-blob-storage-env:
+	@if [ -z "${BLOB_STORAGE_GCS_BUCKET}" ]; then \
+                echo "Error: BLOB_STORAGE_GCS_BUCKET must be defined."; \
+                exit 1; \
+        fi
