syz-cluster: add a DB migration job
The job can be created by a CD to apply the missing DB migrations.
Add a Makefile target to prepare the job's description.

diff --git a/syz-cluster/Makefile b/syz-cluster/Makefile
--- a/syz-cluster/Makefile
+++ b/syz-cluster/Makefile
@@ -65,3 +65,10 @@ restart-spanner: build-db-mgmt
 
 k8s-config-dev:
 	@kubectl kustomize ./overlays/minikube/ | IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${IMAGE_TAG} envsubst
+
+migrate-job.yaml:
+	@if [ -z "${SPANNER_DATABASE_URI}" ]; then \
+                echo "Error: SPANNER_DATABASE_URI must be defined."; \
+                exit 1; \
+        fi
+	@cat db-mgmt/migrate-job.yaml | IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_TAG=${IMAGE_TAG} envsubst
